"""Unit coverage for the ``PostgresClient.tenant_scope`` helper + migration 037.

The integration-level "User A cannot read User B" proof lives in
``tests/integration/test_rls_isolation.py`` (skipped without a real Postgres).
These unit tests pin the contract that the helper always installs the
session variable inside a transaction, so the RLS policies from migration
037 can rely on ``current_setting('app.current_user_id', true)``.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest


class _FakeTxCtx:
    """Mimic asyncpg's connection.transaction() async context manager."""

    def __init__(self) -> None:
        self.entered = 0
        self.exited = 0

    async def __aenter__(self) -> None:
        self.entered += 1
        return None

    async def __aexit__(self, *_: object) -> bool:
        self.exited += 1
        return False


class _FakeConn:
    def __init__(self) -> None:
        self.execute = AsyncMock()
        self._tx = _FakeTxCtx()

    def transaction(self) -> _FakeTxCtx:
        return self._tx


class _FakePoolAcquireCtx:
    def __init__(self, conn: _FakeConn) -> None:
        self._conn = conn

    async def __aenter__(self) -> _FakeConn:
        return self._conn

    async def __aexit__(self, *_: object) -> bool:
        return False


class _FakePool:
    def __init__(self, conn: _FakeConn) -> None:
        self._conn = conn

    def acquire(self) -> _FakePoolAcquireCtx:
        return _FakePoolAcquireCtx(self._conn)


@pytest.mark.asyncio
async def test_tenant_scope_sets_session_variable_in_a_transaction() -> None:
    from src.databases.postgres import PostgresClient

    conn = _FakeConn()
    pool = _FakePool(conn)

    client = PostgresClient()
    client._use_supabase_client = MagicMock(return_value=False)  # type: ignore[attr-defined]
    client._get_client = AsyncMock(return_value=pool)  # type: ignore[attr-defined]

    async with client.tenant_scope("user-123") as yielded:
        assert yielded is conn

    assert conn._tx.entered == 1, "must wrap in a tx so the setting is local"
    assert conn._tx.exited == 1, "tx must exit (resets the setting)"
    conn.execute.assert_awaited_once_with("SELECT set_config('app.current_user_id', $1, true)", "user-123")


@pytest.mark.asyncio
async def test_tenant_scope_yields_none_for_supabase_client() -> None:
    """Supabase RLS uses auth.uid() from the JWT — no session variable
    needed; the helper must yield cleanly so callers don't crash."""
    from src.databases.postgres import PostgresClient

    client = PostgresClient()
    client._use_supabase_client = MagicMock(return_value=True)  # type: ignore[attr-defined]
    client._get_client = AsyncMock()  # type: ignore[attr-defined]

    async with client.tenant_scope("anything") as yielded:
        assert yielded is None


@pytest.mark.asyncio
async def test_tenant_scope_coerces_non_string_user_id() -> None:
    """UUIDs, ints, anything stringifiable is accepted. Prevents an edge
    case where a caller passes an integer id and asyncpg barfs."""
    from src.databases.postgres import PostgresClient

    conn = _FakeConn()
    pool = _FakePool(conn)

    client = PostgresClient()
    client._use_supabase_client = MagicMock(return_value=False)  # type: ignore[attr-defined]
    client._get_client = AsyncMock(return_value=pool)  # type: ignore[attr-defined]

    async with client.tenant_scope(42):  # type: ignore[arg-type]
        pass

    args, _ = conn.execute.call_args
    assert args[1] == "42"


def _load_migration_037():
    """Load the 037 migration module by file path.

    Alembic revision files start with a digit, which is not a valid Python
    module name — regular ``import`` cannot reach them. Alembic itself
    loads them via importlib.util.
    """
    import importlib.util
    from pathlib import Path

    repo_root = Path(__file__).resolve().parents[2]
    path = repo_root / "alembic" / "versions" / "037_rls_tenant_scoped_app_policies.py"
    spec = importlib.util.spec_from_file_location("rls037", str(path))
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_migration_037_uses_session_variable_everywhere() -> None:
    """Every policy generated by 037 must reference current_setting for the
    app user. Catches a regression where someone copy-pastes a policy that
    falls back to USING(true)."""
    m = _load_migration_037()

    assert m._APP_USER == "current_setting('app.current_user_id', true)"
    for table, using, check in m._POLICIES:
        assert m._APP_USER in using, f"{table} USING clause skips session variable"
        assert m._APP_USER in check, f"{table} WITH CHECK skips session variable"
        assert "true" not in using.lower().replace("current_setting('app.current_user_id', true)", ""), (
            f"{table} USING still contains a bare TRUE — policy would be permissive"
        )


def test_migration_037_covers_the_critical_tenant_tables() -> None:
    """Pin the list of tightened tables so a future contributor cannot
    accidentally drop one during a merge conflict."""
    m = _load_migration_037()

    expected = {
        "users",
        "offer_participants",
        "payments",
        "notifications",
        "buildings",
        "building_residents",
        "offers",
        "file_uploads",
        "escalations",
        "chat_messages",
        "invoices",
        "payment_splits",
        "contractor_reviews",
    }
    actual = {t for t, _u, _c in m._POLICIES}
    assert actual == expected, (
        f"migration 037 policy set drift: missing={expected - actual} unexpected={actual - expected}"
    )
